version: '3'
services:
  db:
    ports:
      - 27017:27017
    volumes:
      - ../data/db:/data/db
    env_file:
      - ./cargo.env

  backend:
    command: flask run
    ports:
      - 5000:5000
    env_file:
      - ./cargo.env
