version: '3'
services:
  db:
    image: mongo:3.6.1
    restart: unless-stopped
    networks:
      - backend

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    entrypoint: /code/docker/backend/entrypoint.sh
    volumes:
      - ..:/code
    depends_on:
      - db
    networks:
      - backend


networks:
  backend:
    driver: bridge
